import { 
  Brain, 
  Code, 
  Database, 
  LayoutTemplate, 
  Lightbulb, 
  Calculator, 
  Globe, 
  GitBranch, 
  Rocket, 
  Server, 
  Shield, 
  Music,
  BookOpen,
  PenTool,
  Palette,
  Microscope,
  Heart,
  Beaker,
  GraduationCap
} from "lucide-react";

import React from "react";

// 创建一个带有圆形蓝色背景的图标组件
const IconWithBackground = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center">
      {children}
    </div>
  );
};

export interface TreeNode {
  id: string
  title: string
  description: string
  icon: React.ReactNode
  color: string
  difficulty: string
  estimatedTime: string
  recommendedCourse?: {
    title: string
    provider: string
    url: string
  }
  children?: TreeNode[]
  expanded?: boolean
}

export interface LearningPath {
  id: string
  title: string
  description: string
  icon: React.ReactNode
  color: string
  data: TreeNode
}

export const learningPaths: LearningPath[] = [
  {
    id: "computer-science",
    title: "计算机科学",
    description: "系统学习计算机基础和编程技术",
    icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
    color: "bg-blue-500",
    data: {
      id: "root",
      title: "计算机科学",
      description: "计算机和编程的基础",
      icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
      color: "bg-blue-500",
      difficulty: "入门",
      estimatedTime: "4-5年",
      recommendedCourse: {
        title: "计算机科学导论",
        provider: "中国大学MOOC",
        url: "https://example.com/cs-intro",
      },
      expanded: true,
      children: [
        {
          id: "programming-basics",
          title: "编程基础",
          description: "学习编程和算法的基础知识",
          icon: <IconWithBackground><BookOpen className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-green-500",
          difficulty: "入门",
          estimatedTime: "3-6个月",
          recommendedCourse: {
            title: "Python编程基础",
            provider: "网易云课堂",
            url: "https://example.com/python-basics",
          },
          expanded: true,
          children: [
            {
              id: "python",
              title: "Python编程",
              description: "以Python作为你的第一门编程语言",
              icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-yellow-500",
              difficulty: "入门",
              estimatedTime: "4-8周",
              recommendedCourse: {
                title: "Python零基础入门",
                provider: "慕课网",
                url: "https://example.com/python-zero",
              },
              children: [],
            },
            {
              id: "data-structures",
              title: "数据结构",
              description: "学习数组、链表、栈和队列",
              icon: <IconWithBackground><Database className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-purple-500",
              difficulty: "中级",
              estimatedTime: "6-10周",
              recommendedCourse: {
                title: "数据结构与算法",
                provider: "学堂在线",
                url: "https://example.com/data-structures",
              },
              children: [],
            },
            {
              id: "algorithms",
              title: "算法基础",
              description: "掌握排序、搜索和图算法",
              icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-pink-500",
              difficulty: "中级",
              estimatedTime: "8-12周",
              recommendedCourse: {
                title: "算法设计与分析",
                provider: "Coursera",
                url: "https://example.com/algorithms",
              },
              children: [],
            },
            {
              id: "programming-paradigms",
              title: "编程范式",
              description: "面向对象、函数式和响应式编程",
              icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-indigo-500",
              difficulty: "中级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "编程范式与设计模式",
                provider: "极客时间",
                url: "https://example.com/paradigms",
              },
              children: [],
            },
          ]
        },
        {
          id: "computer-systems",
          title: "计算机系统",
          description: "了解计算机底层工作原理",
          icon: <IconWithBackground><Server className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-orange-500",
          difficulty: "中级",
          estimatedTime: "6-9个月",
          recommendedCourse: {
            title: "计算机系统原理",
            provider: "中国大学MOOC",
            url: "https://example.com/computer-systems",
          },
          expanded: true,
          children: [
            {
              id: "computer-architecture",
              title: "计算机架构",
              description: "学习CPU、内存和系统设计",
              icon: <IconWithBackground><Server className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-red-500",
              difficulty: "中级",
              estimatedTime: "8-12周",
              recommendedCourse: {
                title: "计算机组成原理",
                provider: "哈尔滨工业大学MOOC",
                url: "https://example.com/computer-architecture",
              },
              children: [],
            },
            {
              id: "operating-systems",
              title: "操作系统",
              description: "学习进程管理、内存和文件系统",
              icon: <IconWithBackground><Server className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-blue-600",
              difficulty: "高级",
              estimatedTime: "10-14周",
              recommendedCourse: {
                title: "操作系统原理与实践",
                provider: "清华大学MOOC",
                url: "https://example.com/operating-systems",
              },
              children: [],
            },
            {
              id: "computer-networks",
              title: "计算机网络",
              description: "网络协议、架构和安全",
              icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-cyan-500",
              difficulty: "中级",
              estimatedTime: "8-12周",
              recommendedCourse: {
                title: "计算机网络原理",
                provider: "中国大学MOOC",
                url: "https://example.com/computer-networks",
              },
              children: [],
            },
            {
              id: "database-systems",
              title: "数据库系统",
              description: "关系型与非关系型数据库设计",
              icon: <IconWithBackground><Database className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-emerald-600",
              difficulty: "中级",
              estimatedTime: "6-10周",
              recommendedCourse: {
                title: "数据库系统概念",
                provider: "网易云课堂",
                url: "https://example.com/database-systems",
              },
              children: [],
            },
          ],
        },
        {
          id: "web-development",
          title: "Web开发",
          description: "构建网站和Web应用",
          icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-cyan-500",
          difficulty: "中级",
          estimatedTime: "8-12个月",
          recommendedCourse: {
            title: "全栈Web开发",
            provider: "腾讯课堂",
            url: "https://example.com/web-dev",
          },
          expanded: true,
          children: [
            {
              id: "frontend",
              title: "前端开发",
              description: "学习HTML、CSS和JavaScript",
              icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-indigo-500",
              difficulty: "入门",
              estimatedTime: "8-12周",
              recommendedCourse: {
                title: "前端开发入门到精通",
                provider: "极客时间",
                url: "https://example.com/frontend",
              },
              children: [],
            },
            {
              id: "javascript-frameworks",
              title: "JavaScript框架",
              description: "React、Vue、Angular等现代框架",
              icon: <IconWithBackground><LayoutTemplate className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-blue-500",
              difficulty: "中级",
              estimatedTime: "8-12周",
              recommendedCourse: {
                title: "React/Vue实战开发",
                provider: "慕课网",
                url: "https://example.com/js-frameworks",
              },
              children: [],
            },
            {
              id: "backend",
              title: "后端开发",
              description: "学习服务器端编程和数据库",
              icon: <IconWithBackground><Database className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-emerald-500",
              difficulty: "中级",
              estimatedTime: "10-14周",
              recommendedCourse: {
                title: "Node.js后端开发实战",
                provider: "慕课网",
                url: "https://example.com/backend",
              },
              children: [],
            },
            {
              id: "web-deployment",
              title: "Web部署与DevOps",
              description: "CI/CD、云服务和容器化",
              icon: <IconWithBackground><Server className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-slate-600",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "Web应用部署与运维",
                provider: "阿里云大学",
                url: "https://example.com/web-deployment",
              },
              children: [],
            },
          ],
        },
        {
          id: "software-engineering",
          title: "软件工程",
          description: "软件开发流程与最佳实践",
          icon: <IconWithBackground><GitBranch className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-violet-600",
          difficulty: "中级",
          estimatedTime: "4-6个月",
          recommendedCourse: {
            title: "软件工程实践",
            provider: "Coursera",
            url: "https://example.com/software-engineering",
          },
          expanded: true,
          children: [
            {
              id: "agile-development",
              title: "敏捷开发",
              description: "Scrum、看板和极限编程",
              icon: <IconWithBackground><GitBranch className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-teal-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "敏捷软件开发",
                provider: "极客时间",
                url: "https://example.com/agile",
              },
              children: [],
            },
            {
              id: "design-patterns",
              title: "设计模式",
              description: "常用软件设计模式与应用",
              icon: <IconWithBackground><LayoutTemplate className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-600",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "设计模式精讲",
                provider: "慕课网",
                url: "https://example.com/design-patterns",
              },
              children: [],
            },
            {
              id: "code-quality",
              title: "代码质量",
              description: "代码规范、自动化测试和重构",
              icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-rose-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "高质量代码与重构",
                provider: "极客时间",
                url: "https://example.com/code-quality",
              },
              children: [],
            },
          ],
        },
        {
          id: "advanced-topics",
          title: "高级主题",
          description: "计算机科学的专业领域",
          icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-violet-500",
          difficulty: "高级",
          estimatedTime: "1-2年",
          recommendedCourse: {
            title: "计算机科学前沿技术",
            provider: "Coursera",
            url: "https://example.com/advanced-cs",
          },
          expanded: true,
          children: [
            {
              id: "ai-ml",
              title: "人工智能与机器学习",
              description: "学习人工智能和机器学习",
              icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-fuchsia-500",
              difficulty: "高级",
              estimatedTime: "6-12个月",
              recommendedCourse: {
                title: "机器学习与深度学习实战",
                provider: "吴恩达课程",
                url: "https://example.com/ai-ml",
              },
              children: [],
            },
            {
              id: "cloud-computing",
              title: "云计算",
              description: "云服务架构与实现",
              icon: <IconWithBackground><Server className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-sky-500",
              difficulty: "高级",
              estimatedTime: "4-8个月",
              recommendedCourse: {
                title: "AWS/Azure/GCP云计算实战",
                provider: "腾讯课堂",
                url: "https://example.com/cloud-computing",
              },
              children: [],
            },
            {
              id: "cybersecurity",
              title: "网络安全",
              description: "学习安全原则和实践",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-slate-700",
              difficulty: "高级",
              estimatedTime: "6-12个月",
              recommendedCourse: {
                title: "网络安全与渗透测试",
                provider: "黑马程序员",
                url: "https://example.com/cybersecurity",
              },
              children: [],
            },
            {
              id: "blockchain",
              title: "区块链技术",
              description: "分布式账本与智能合约",
              icon: <IconWithBackground><Database className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-600",
              difficulty: "高级",
              estimatedTime: "4-8个月",
              recommendedCourse: {
                title: "区块链技术与应用",
                provider: "Coursera",
                url: "https://example.com/blockchain",
              },
              children: [],
            },
          ],
        },
      ]
    }
  },
  {
    id: "data-science",
    title: "数据科学",
    description: "数据分析与机器学习实践",
    icon: <IconWithBackground><Calculator className="h-5 w-5 text-white" /></IconWithBackground>,
    color: "bg-emerald-500",
    data: {
      id: "root",
      title: "数据科学",
      description: "数据分析与建模",
      icon: <IconWithBackground><Calculator className="h-5 w-5 text-white" /></IconWithBackground>,
      color: "bg-emerald-500",
      difficulty: "中级",
      estimatedTime: "2-3年",
      recommendedCourse: {
        title: "数据科学入门",
        provider: "Coursera",
        url: "https://example.com/data-science-intro",
      },
      expanded: true,
      children: [
        {
          id: "math-foundations",
          title: "数学基础",
          description: "数据科学的数学基础",
          icon: <IconWithBackground><Calculator className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-blue-500",
          difficulty: "入门到中级",
          estimatedTime: "3-4个月",
          recommendedCourse: {
            title: "数据科学的数学基础",
            provider: "网易云课堂",
            url: "https://example.com/math-for-ds",
          },
          expanded: true,
          children: [
            {
              id: "linear-algebra",
              title: "线性代数",
              description: "向量、矩阵与变换",
              icon: <IconWithBackground><Calculator className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-sky-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "数据科学中的线性代数",
                provider: "学堂在线",
                url: "https://example.com/linear-algebra",
              },
              children: [],
            },
            {
              id: "calculus",
              title: "微积分",
              description: "导数、积分与优化",
              icon: <IconWithBackground><Calculator className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-violet-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "数据科学中的微积分",
                provider: "中国大学MOOC",
                url: "https://example.com/calculus",
              },
              children: [],
            },
            {
              id: "statistics",
              title: "统计学",
              description: "概率论与统计推断",
              icon: <IconWithBackground><Calculator className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-500",
              difficulty: "中级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "统计学与概率论",
                provider: "Coursera",
                url: "https://example.com/statistics",
              },
              children: [],
            },
          ]
        },
        {
          id: "programming-for-ds",
          title: "数据科学编程",
          description: "Python与数据分析库",
          icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-indigo-500",
          difficulty: "入门到中级",
          estimatedTime: "4-6个月",
          recommendedCourse: {
            title: "Python数据分析",
            provider: "慕课网",
            url: "https://example.com/python-data",
          },
          expanded: true,
          children: [
            {
              id: "python-basics",
              title: "Python基础",
              description: "Python语法与数据结构",
              icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-sky-500",
              difficulty: "入门",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "Python编程基础",
                provider: "网易云课堂",
                url: "https://example.com/python-basics",
              },
              children: [],
            },
            {
              id: "data-analysis",
              title: "数据分析工具",
              description: "NumPy、Pandas与数据处理",
              icon: <IconWithBackground><Database className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-teal-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "Python数据分析库",
                provider: "慕课网",
                url: "https://example.com/pandas",
              },
              children: [],
            },
            {
              id: "data-visualization",
              title: "数据可视化",
              description: "Matplotlib、Seaborn与可视化",
              icon: <IconWithBackground><LayoutTemplate className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-rose-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "Python数据可视化",
                provider: "B站教学",
                url: "https://example.com/visualization",
              },
              children: [],
            },
          ]
        },
        {
          id: "machine-learning",
          title: "机器学习",
          description: "监督与无监督学习算法",
          icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-violet-600",
          difficulty: "中级到高级",
          estimatedTime: "6-8个月",
          recommendedCourse: {
            title: "机器学习基础",
            provider: "Coursera",
            url: "https://example.com/ml-basics",
          },
          expanded: true,
          children: [
            {
              id: "supervised-learning",
              title: "监督学习",
              description: "回归与分类算法",
              icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-blue-500",
              difficulty: "中级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "监督学习算法详解",
                provider: "网易云课堂",
                url: "https://example.com/supervised",
              },
              children: [],
            },
            {
              id: "unsupervised-learning",
              title: "无监督学习",
              description: "聚类与降维算法",
              icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "无监督学习方法",
                provider: "极客时间",
                url: "https://example.com/unsupervised",
              },
              children: [],
            },
            {
              id: "model-evaluation",
              title: "模型评估",
              description: "模型选择与验证方法",
              icon: <IconWithBackground><Calculator className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-emerald-600",
              difficulty: "中级",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "机器学习模型评估",
                provider: "B站教学",
                url: "https://example.com/model-eval",
              },
              children: [],
            },
          ]
        },
        {
          id: "data-engineering",
          title: "数据工程",
          description: "大数据处理与数据架构",
          icon: <IconWithBackground><Database className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-cyan-600",
          difficulty: "中级到高级",
          estimatedTime: "4-6个月",
          recommendedCourse: {
            title: "数据工程基础",
            provider: "极客时间",
            url: "https://example.com/data-engineering",
          },
          expanded: true,
          children: [
            {
              id: "big-data",
              title: "大数据处理",
              description: "Hadoop、Spark与分布式计算",
              icon: <IconWithBackground><Database className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-500",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "大数据处理框架",
                provider: "阿里云大学",
                url: "https://example.com/big-data",
              },
              children: [],
            },
            {
              id: "data-pipelines",
              title: "数据管道",
              description: "ETL流程与数据集成",
              icon: <IconWithBackground><Server className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-teal-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "数据管道与ETL",
                provider: "腾讯云大学",
                url: "https://example.com/data-pipelines",
              },
              children: [],
            },
            {
              id: "data-warehousing",
              title: "数据仓库",
              description: "数据仓库设计与实现",
              icon: <IconWithBackground><Database className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-blue-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "现代数据仓库",
                provider: "极客时间",
                url: "https://example.com/data-warehouse",
              },
              children: [],
            },
          ]
        },
        {
          id: "applied-data-science",
          title: "应用数据科学",
          description: "行业应用与实践项目",
          icon: <IconWithBackground><Lightbulb className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-green-600",
          difficulty: "高级",
          estimatedTime: "6-10个月",
          recommendedCourse: {
            title: "数据科学实战项目",
            provider: "Kaggle",
            url: "https://example.com/applied-ds",
          },
          expanded: true,
          children: [
            {
              id: "business-analytics",
              title: "商业分析",
              description: "业务数据分析与决策",
              icon: <IconWithBackground><Lightbulb className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-blue-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "商业数据分析",
                provider: "网易云课堂",
                url: "https://example.com/business-analytics",
              },
              children: [],
            },
            {
              id: "nlp",
              title: "自然语言处理",
              description: "文本分析与语言模型",
              icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-violet-600",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "NLP与文本分析",
                provider: "Coursera",
                url: "https://example.com/nlp",
              },
              children: [],
            },
            {
              id: "time-series",
              title: "时间序列分析",
              description: "预测和趋势分析",
              icon: <IconWithBackground><Calculator className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-cyan-600",
              difficulty: "高级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "时间序列预测",
                provider: "学堂在线",
                url: "https://example.com/time-series",
              },
              children: [],
            },
          ]
        }
      ]
    }
  },
  {
    id: "artificial-intelligence",
    title: "人工智能",
    description: "研究机器学习与深度学习算法",
    icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
    color: "bg-fuchsia-500",
    data: {
      id: "root",
      title: "人工智能",
      description: "AI与深度学习基础",
      icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
      color: "bg-fuchsia-500",
      difficulty: "中级到高级",
      estimatedTime: "2-3年",
      recommendedCourse: {
        title: "人工智能导论",
        provider: "Coursera",
        url: "https://example.com/ai-intro",
      },
      expanded: true,
      children: [
        {
          id: "ai-prerequisites",
          title: "AI先修知识",
          description: "人工智能所需的基础知识",
          icon: <IconWithBackground><BookOpen className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-blue-500",
          difficulty: "入门到中级",
          estimatedTime: "4-6个月",
          recommendedCourse: {
            title: "AI数学基础",
            provider: "网易云课堂",
            url: "https://example.com/ai-math",
          },
          expanded: true,
          children: [
            {
              id: "ai-math",
              title: "AI数学基础",
              description: "线性代数、概率论与微积分",
              icon: <IconWithBackground><Calculator className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-indigo-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "AI数学基础课程",
                provider: "中国大学MOOC",
                url: "https://example.com/ai-mathematics",
              },
              children: [],
            },
            {
              id: "programming-for-ai",
              title: "AI编程基础",
              description: "Python与AI编程库",
              icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-cyan-600",
              difficulty: "中级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "Python与AI编程",
                provider: "慕课网",
                url: "https://example.com/python-ai",
              },
              children: [],
            },
            {
              id: "data-for-ai",
              title: "AI数据处理",
              description: "数据预处理与特征工程",
              icon: <IconWithBackground><Database className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-emerald-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "AI数据准备与处理",
                provider: "极客时间",
                url: "https://example.com/ai-data",
              },
              children: [],
            },
          ]
        },
        {
          id: "machine-learning-ai",
          title: "机器学习",
          description: "机器学习算法与应用",
          icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-violet-600",
          difficulty: "中级",
          estimatedTime: "6-8个月",
          recommendedCourse: {
            title: "机器学习基础与实践",
            provider: "Coursera",
            url: "https://example.com/ml-fundamentals",
          },
          expanded: true,
          children: [
            {
              id: "ml-fundamentals",
              title: "机器学习基础",
              description: "监督与无监督学习",
              icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-blue-500",
              difficulty: "中级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "机器学习算法详解",
                provider: "网易云课堂",
                url: "https://example.com/ml-algorithms",
              },
              children: [],
            },
            {
              id: "ml-frameworks",
              title: "机器学习框架",
              description: "Scikit-learn与TensorFlow",
              icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-600",
              difficulty: "中级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "机器学习框架实战",
                provider: "极客时间",
                url: "https://example.com/ml-frameworks",
              },
              children: [],
            },
            {
              id: "ml-project",
              title: "机器学习项目",
              description: "端到端ML项目实战",
              icon: <IconWithBackground><Rocket className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-emerald-600",
              difficulty: "中级到高级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "机器学习项目实战",
                provider: "慕课网",
                url: "https://example.com/ml-projects",
              },
              children: [],
            },
          ]
        },
        {
          id: "deep-learning",
          title: "深度学习",
          description: "神经网络与深度学习模型",
          icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-fuchsia-600",
          difficulty: "高级",
          estimatedTime: "8-10个月",
          recommendedCourse: {
            title: "深度学习专项课程",
            provider: "Coursera",
            url: "https://example.com/deep-learning",
          },
          expanded: true,
          children: [
            {
              id: "neural-networks",
              title: "神经网络基础",
              description: "前馈神经网络与反向传播",
              icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-indigo-600",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "神经网络与深度学习",
                provider: "网易云课堂",
                url: "https://example.com/neural-networks",
              },
              children: [],
            },
            {
              id: "cnn",
              title: "卷积神经网络",
              description: "CNN架构与计算机视觉",
              icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-cyan-600",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "卷积神经网络详解",
                provider: "极客时间",
                url: "https://example.com/cnn",
              },
              children: [],
            },
            {
              id: "rnn-transformers",
              title: "RNN与Transformer",
              description: "序列模型与注意力机制",
              icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-rose-600",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "序列模型与Transformer",
                provider: "Coursera",
                url: "https://example.com/transformers",
              },
              children: [],
            },
          ]
        },
        {
          id: "nlp",
          title: "自然语言处理",
          description: "NLP技术与应用",
          icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-sky-600",
          difficulty: "高级",
          estimatedTime: "6-8个月",
          recommendedCourse: {
            title: "自然语言处理实战",
            provider: "极客时间",
            url: "https://example.com/nlp-ai",
          },
          expanded: true,
          children: [
            {
              id: "text-processing",
              title: "文本处理基础",
              description: "文本预处理与表示",
              icon: <IconWithBackground><BookOpen className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-blue-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "NLP文本处理基础",
                provider: "网易云课堂",
                url: "https://example.com/text-processing",
              },
              children: [],
            },
            {
              id: "language-models",
              title: "语言模型",
              description: "统计与神经语言模型",
              icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-violet-600",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "深度学习语言模型",
                provider: "B站教学",
                url: "https://example.com/language-models",
              },
              children: [],
            },
            {
              id: "nlp-applications",
              title: "NLP应用",
              description: "情感分析、文本生成与对话系统",
              icon: <IconWithBackground><Lightbulb className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-600",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "NLP应用实战",
                provider: "极客时间",
                url: "https://example.com/nlp-applications",
              },
              children: [],
            },
          ]
        },
        {
          id: "computer-vision",
          title: "计算机视觉",
          description: "图像与视频处理技术",
          icon: <IconWithBackground><LayoutTemplate className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-amber-600",
          difficulty: "高级",
          estimatedTime: "6-8个月",
          recommendedCourse: {
            title: "计算机视觉实战",
            provider: "Coursera",
            url: "https://example.com/computer-vision",
          },
          expanded: true,
          children: [
            {
              id: "image-processing",
              title: "图像处理基础",
              description: "滤波、变换与特征提取",
              icon: <IconWithBackground><LayoutTemplate className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-blue-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "数字图像处理",
                provider: "中国大学MOOC",
                url: "https://example.com/image-processing",
              },
              children: [],
            },
            {
              id: "object-detection",
              title: "目标检测与分割",
              description: "YOLO、Mask R-CNN等模型",
              icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-600",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "目标检测与分割实战",
                provider: "极客时间",
                url: "https://example.com/object-detection",
              },
              children: [],
            },
            {
              id: "generative-vision",
              title: "生成视觉模型",
              description: "图像生成与扩散模型",
              icon: <IconWithBackground><Brain className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-rose-600",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "图像生成与Diffusion模型",
                provider: "网易云课堂",
                url: "https://example.com/generative-vision",
              },
              children: [],
            },
          ]
        },
        {
          id: "ai-ethics",
          title: "AI伦理与实践",
          description: "AI应用与伦理问题",
          icon: <IconWithBackground><Lightbulb className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-rose-500",
          difficulty: "中级到高级",
          estimatedTime: "3-4个月",
          recommendedCourse: {
            title: "AI伦理与责任",
            provider: "Coursera",
            url: "https://example.com/ai-ethics",
          },
          expanded: true,
          children: [
            {
              id: "ai-bias",
              title: "AI偏见与公平性",
              description: "模型偏见检测与缓解",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-blue-500",
              difficulty: "中级",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "AI公平性与伦理",
                provider: "网易云课堂",
                url: "https://example.com/ai-fairness",
              },
              children: [],
            },
            {
              id: "ai-safety",
              title: "AI安全与隐私",
              description: "安全AI与隐私保护",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-indigo-600",
              difficulty: "高级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "AI安全与隐私保护",
                provider: "极客时间",
                url: "https://example.com/ai-safety",
              },
              children: [],
            },
            {
              id: "ai-product",
              title: "AI产品开发",
              description: "从原型到产品的AI应用",
              icon: <IconWithBackground><Lightbulb className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-emerald-600",
              difficulty: "高级",
              estimatedTime: "8-12周",
              recommendedCourse: {
                title: "AI产品设计与开发",
                provider: "极客时间",
                url: "https://example.com/ai-product",
              },
              children: [],
            },
          ]
        }
      ]
    }
  },
  {
    id: "web-development",
    title: "Web开发",
    description: "学习前后端开发与网站架构",
    icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
    color: "bg-cyan-500",
    data: {
      id: "root",
      title: "Web开发",
      description: "全栈Web开发技能",
      icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
      color: "bg-cyan-500",
      difficulty: "中级",
      estimatedTime: "2-3年",
      recommendedCourse: {
        title: "Web开发全栈工程师",
        provider: "慕课网",
        url: "https://example.com/web-dev",
      },
      expanded: true,
      children: [
        {
          id: "web-fundamentals",
          title: "Web基础",
          description: "HTML、CSS与网络基础",
          icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-blue-500",
          difficulty: "入门",
          estimatedTime: "2-3个月",
          recommendedCourse: {
            title: "Web开发基础",
            provider: "腾讯课堂",
            url: "https://example.com/web-basics",
          },
          expanded: true,
          children: [
            {
              id: "internet-basics",
              title: "互联网基础",
              description: "HTTP协议与网络原理",
              icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-cyan-600",
              difficulty: "入门",
              estimatedTime: "2-3周",
              recommendedCourse: {
                title: "互联网工作原理",
                provider: "中国大学MOOC",
                url: "https://example.com/internet-basics",
              },
              children: [],
            },
            {
              id: "html-css",
              title: "HTML与CSS",
              description: "Web页面结构与样式",
              icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-500",
              difficulty: "入门",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "HTML与CSS入门",
                provider: "B站教学",
                url: "https://example.com/html-css",
              },
              children: [],
            },
            {
              id: "web-standards",
              title: "Web标准",
              description: "可访问性与语义化HTML",
              icon: <IconWithBackground><BookOpen className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-teal-600",
              difficulty: "入门",
              estimatedTime: "2-3周",
              recommendedCourse: {
                title: "现代Web标准",
                provider: "极客时间",
                url: "https://example.com/web-standards",
              },
              children: [],
            },
          ]
        },
        {
          id: "frontend",
          title: "前端开发",
          description: "HTML、CSS和JavaScript",
          icon: <LayoutTemplate className="h-5 w-5 text-white" />,
          color: "bg-amber-500",
          difficulty: "入门",
          estimatedTime: "4-6个月",
          recommendedCourse: {
            title: "前端开发实战",
            provider: "腾讯课堂",
            url: "https://example.com/frontend",
          },
          expanded: true,
          children: [
            {
              id: "html-css",
              title: "HTML与CSS",
              description: "网页结构与样式",
              icon: <LayoutTemplate className="h-5 w-5 text-white" />,
              color: "bg-orange-500",
              difficulty: "入门",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "HTML5+CSS3基础",
                provider: "慕课网",
                url: "https://example.com/html-css",
              },
              children: [],
            },
            {
              id: "javascript",
              title: "JavaScript基础",
              description: "JS语法与DOM操作",
              icon: <Code className="h-5 w-5 text-white" />,
              color: "bg-yellow-500",
              difficulty: "入门",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "JavaScript从入门到精通",
                provider: "极客时间",
                url: "https://example.com/javascript",
              },
              children: [],
            },
            {
              id: "responsive-design",
              title: "响应式设计",
              description: "移动优先与多设备适配",
              icon: <LayoutTemplate className="h-5 w-5 text-white" />,
              color: "bg-teal-500",
              difficulty: "中级",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "响应式Web设计",
                provider: "网易云课堂",
                url: "https://example.com/responsive",
              },
              children: [],
            },
            {
              id: "css-frameworks",
              title: "CSS框架",
              description: "Bootstrap、Tailwind CSS",
              icon: <LayoutTemplate className="h-5 w-5 text-white" />,
              color: "bg-blue-500",
              difficulty: "入门",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "Tailwind CSS实战",
                provider: "慕课网",
                url: "https://example.com/css-frameworks",
              },
              children: [],
            },
          ]
        },
        {
          id: "js-advanced",
          title: "JavaScript进阶",
          description: "现代JavaScript编程",
          icon: <Code className="h-5 w-5 text-white" />,
          color: "bg-yellow-600",
          difficulty: "中级",
          estimatedTime: "3-4个月",
          recommendedCourse: {
            title: "JavaScript高级程序设计",
            provider: "极客时间",
            url: "https://example.com/js-advanced",
          },
          expanded: true,
          children: [
            {
              id: "es6-plus",
              title: "ES6+特性",
              description: "现代JavaScript语言特性",
              icon: <Code className="h-5 w-5 text-white" />,
              color: "bg-amber-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "ES6+实战指南",
                provider: "慕课网",
                url: "https://example.com/es6",
              },
              children: [],
            },
            {
              id: "typescript",
              title: "TypeScript",
              description: "类型安全的JavaScript超集",
              icon: <Code className="h-5 w-5 text-white" />,
              color: "bg-blue-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "TypeScript入门与实践",
                provider: "极客时间",
                url: "https://example.com/typescript",
              },
              children: [],
            },
            {
              id: "async-js",
              title: "异步JavaScript",
              description: "Promise、Async/Await",
              icon: <Code className="h-5 w-5 text-white" />,
              color: "bg-indigo-500",
              difficulty: "中级",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "JavaScript异步编程",
                provider: "网易云课堂",
                url: "https://example.com/async-js",
              },
              children: [],
            },
          ]
        },
        {
          id: "frontend-frameworks",
          title: "前端框架",
          description: "现代JavaScript框架",
          icon: <LayoutTemplate className="h-5 w-5 text-white" />,
          color: "bg-blue-600",
          difficulty: "中级",
          estimatedTime: "6-8个月",
          recommendedCourse: {
            title: "现代前端框架实战",
            provider: "腾讯课堂",
            url: "https://example.com/frontend-frameworks",
          },
          expanded: true,
          children: [
            {
              id: "react",
              title: "React.js",
              description: "组件化UI开发",
              icon: <Code className="h-5 w-5 text-white" />,
              color: "bg-cyan-500",
              difficulty: "中级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "React全家桶实战",
                provider: "慕课网",
                url: "https://example.com/react",
              },
              children: [],
            },
            {
              id: "vue",
              title: "Vue.js",
              description: "渐进式JavaScript框架",
              icon: <Code className="h-5 w-5 text-white" />,
              color: "bg-emerald-500",
              difficulty: "中级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "Vue3+Vite+TS实战",
                provider: "极客时间",
                url: "https://example.com/vue",
              },
              children: [],
            },
            {
              id: "state-management",
              title: "状态管理",
              description: "Redux、Pinia、Zustand",
              icon: <Database className="h-5 w-5 text-white" />,
              color: "bg-violet-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "前端状态管理精讲",
                provider: "慕课网",
                url: "https://example.com/state-management",
              },
              children: [],
            },
            {
              id: "next-nuxt",
              title: "Next.js/Nuxt.js",
              description: "React与Vue的SSR框架",
              icon: <Globe className="h-5 w-5 text-white" />,
              color: "bg-slate-700",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "Next.js全栈应用开发",
                provider: "腾讯课堂",
                url: "https://example.com/next-js",
              },
              children: [],
            },
          ]
        },
        {
          id: "backend",
          title: "后端开发",
          description: "服务器端编程与API开发",
          icon: <Server className="h-5 w-5 text-white" />,
          color: "bg-green-600",
          difficulty: "中级",
          estimatedTime: "6-8个月",
          recommendedCourse: {
            title: "后端开发实战",
            provider: "极客时间",
            url: "https://example.com/backend-dev",
          },
          expanded: true,
          children: [
            {
              id: "nodejs",
              title: "Node.js",
              description: "JavaScript服务器端编程",
              icon: <Server className="h-5 w-5 text-white" />,
              color: "bg-green-500",
              difficulty: "中级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "Node.js开发实战",
                provider: "慕课网",
                url: "https://example.com/nodejs",
              },
              children: [],
            },
            {
              id: "express-nest",
              title: "Express/NestJS",
              description: "Node.js后端框架",
              icon: <Server className="h-5 w-5 text-white" />,
              color: "bg-red-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "Express与NestJS开发",
                provider: "极客时间",
                url: "https://example.com/express-nest",
              },
              children: [],
            },
            {
              id: "api-design",
              title: "API设计",
              description: "RESTful与GraphQL",
              icon: <Code className="h-5 w-5 text-white" />,
              color: "bg-indigo-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "Web API设计",
                provider: "网易云课堂",
                url: "https://example.com/api-design",
              },
              children: [],
            },
            {
              id: "authentication",
              title: "身份验证与授权",
              description: "JWT、OAuth和安全",
              icon: <Shield className="h-5 w-5 text-white" />,
              color: "bg-amber-600",
              difficulty: "中级",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "Web安全与认证",
                provider: "极客时间",
                url: "https://example.com/web-auth",
              },
              children: [],
            },
          ]
        },
        {
          id: "databases",
          title: "数据库",
          description: "数据存储与管理",
          icon: <Database className="h-5 w-5 text-white" />,
          color: "bg-amber-600",
          difficulty: "中级",
          estimatedTime: "3-4个月",
          recommendedCourse: {
            title: "Web开发数据库实战",
            provider: "极客时间",
            url: "https://example.com/web-databases",
          },
          expanded: true,
          children: [
            {
              id: "sql",
              title: "SQL数据库",
              description: "MySQL、PostgreSQL",
              icon: <Database className="h-5 w-5 text-white" />,
              color: "bg-blue-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "SQL数据库开发",
                provider: "慕课网",
                url: "https://example.com/sql-db",
              },
              children: [],
            },
            {
              id: "nosql",
              title: "NoSQL数据库",
              description: "MongoDB、Redis",
              icon: <Database className="h-5 w-5 text-white" />,
              color: "bg-green-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "NoSQL数据库实践",
                provider: "网易云课堂",
                url: "https://example.com/nosql",
              },
              children: [],
            },
            {
              id: "orm",
              title: "ORM与数据访问",
              description: "Sequelize、TypeORM、Prisma",
              icon: <Database className="h-5 w-5 text-white" />,
              color: "bg-violet-500",
              difficulty: "中级",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "现代ORM工具实战",
                provider: "极客时间",
                url: "https://example.com/orm",
              },
              children: [],
            },
          ]
        },
        {
          id: "deployment",
          title: "部署与DevOps",
          description: "Web应用上线与运维",
          icon: <Server className="h-5 w-5 text-white" />,
          color: "bg-slate-600",
          difficulty: "中级到高级",
          estimatedTime: "3-4个月",
          recommendedCourse: {
            title: "Web应用部署与运维",
            provider: "阿里云大学",
            url: "https://example.com/web-deployment",
          },
          expanded: true,
          children: [
            {
              id: "ci-cd",
              title: "CI/CD",
              description: "持续集成与部署",
              icon: <GitBranch className="h-5 w-5 text-white" />,
              color: "bg-blue-500",
              difficulty: "中级",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "CI/CD实战指南",
                provider: "极客时间",
                url: "https://example.com/ci-cd",
              },
              children: [],
            },
            {
              id: "containerization",
              title: "容器化",
              description: "Docker与Kubernetes",
              icon: <Server className="h-5 w-5 text-white" />,
              color: "bg-cyan-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "Docker容器化实战",
                provider: "腾讯云大学",
                url: "https://example.com/docker",
              },
              children: [],
            },
            {
              id: "cloud-services",
              title: "云服务",
              description: "AWS、Azure、阿里云",
              icon: <Server className="h-5 w-5 text-white" />,
              color: "bg-indigo-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "云服务部署实战",
                provider: "阿里云大学",
                url: "https://example.com/cloud-deploy",
              },
              children: [],
            },
          ]
        },
        {
          id: "web-performance",
          title: "Web性能优化",
          description: "提升网站速度与用户体验",
          icon: <Rocket className="h-5 w-5 text-white" />,
          color: "bg-rose-600",
          difficulty: "高级",
          estimatedTime: "2-3个月",
          recommendedCourse: {
            title: "Web性能优化实战",
            provider: "极客时间",
            url: "https://example.com/web-performance",
          },
          expanded: true,
          children: [
            {
              id: "front-end-optimization",
              title: "前端优化",
              description: "加载性能与渲染优化",
              icon: <Rocket className="h-5 w-5 text-white" />,
              color: "bg-amber-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "前端性能优化实战",
                provider: "慕课网",
                url: "https://example.com/frontend-optimization",
              },
              children: [],
            },
            {
              id: "back-end-optimization",
              title: "后端优化",
              description: "服务器性能与数据库优化",
              icon: <Server className="h-5 w-5 text-white" />,
              color: "bg-emerald-600",
              difficulty: "高级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "后端性能调优",
                provider: "极客时间",
                url: "https://example.com/backend-optimization",
              },
              children: [],
            },
          ]
        }
      ]
    }
  },
  {
    id: "cybersecurity",
    title: "网络安全",
    description: "网络防御与信息安全技术",
    icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
    color: "bg-slate-700",
    data: {
      id: "root",
      title: "网络安全",
      description: "信息安全与网络防护",
      icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
      color: "bg-slate-700",
      difficulty: "高级",
      estimatedTime: "2-3年",
      recommendedCourse: {
        title: "网络安全基础",
        provider: "网易云课堂",
        url: "https://example.com/cybersecurity-intro",
      },
      expanded: true,
      children: [
        {
          id: "security-fundamentals",
          title: "安全基础",
          description: "网络安全核心概念",
          icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-blue-500",
          difficulty: "入门",
          estimatedTime: "2-3个月",
          recommendedCourse: {
            title: "网络安全入门",
            provider: "网易云课堂",
            url: "https://example.com/security-basics",
          },
          expanded: true,
          children: [
            {
              id: "security-principles",
              title: "安全原则",
              description: "CIA三要素与安全模型",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-indigo-500",
              difficulty: "入门",
              estimatedTime: "2-3周",
              recommendedCourse: {
                title: "信息安全原理",
                provider: "中国大学MOOC",
                url: "https://example.com/security-principles",
              },
              children: [],
            },
            {
              id: "networking-basics",
              title: "网络基础",
              description: "TCP/IP协议与网络架构",
              icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-cyan-600",
              difficulty: "入门",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "计算机网络基础",
                provider: "学堂在线",
                url: "https://example.com/networking-basics",
              },
              children: [],
            },
            {
              id: "cryptography",
              title: "密码学",
              description: "加密算法与密钥管理",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-emerald-600",
              difficulty: "中级",
              estimatedTime: "3-4月",
              recommendedCourse: {
                title: "密码学与网络安全",
                provider: "Coursera",
                url: "https://example.com/cryptography",
              },
              children: [],
            },
          ]
        },
        {
          id: "network-security",
          title: "网络安全",
          description: "保护网络通信与基础设施",
          icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-blue-600",
          difficulty: "中级到高级",
          estimatedTime: "4-6个月",
          recommendedCourse: {
            title: "网络安全实践",
            provider: "极客时间",
            url: "https://example.com/network-security",
          },
          expanded: true,
          children: [
            {
              id: "network-protocols",
              title: "网络协议安全",
              description: "协议漏洞与安全措施",
              icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-cyan-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "网络协议安全详解",
                provider: "极客时间",
                url: "https://example.com/protocol-security",
              },
              children: [],
            },
            {
              id: "firewalls-ids",
              title: "防火墙与入侵检测",
              description: "网络边界防护技术",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-600",
              difficulty: "中级",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "企业防火墙配置与管理",
                provider: "腾讯云大学",
                url: "https://example.com/firewall-ids",
              },
              children: [],
            },
            {
              id: "vpn-security",
              title: "VPN与安全通信",
              description: "安全隧道与远程接入",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-violet-600",
              difficulty: "中级",
              estimatedTime: "2-3周",
              recommendedCourse: {
                title: "企业VPN解决方案",
                provider: "阿里云大学",
                url: "https://example.com/vpn-security",
              },
              children: [],
            },
          ]
        },
        {
          id: "system-security",
          title: "系统安全",
          description: "操作系统与终端安全",
          icon: <IconWithBackground><Server className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-emerald-600",
          difficulty: "中级",
          estimatedTime: "3-4个月",
          recommendedCourse: {
            title: "系统安全加固",
            provider: "极客时间",
            url: "https://example.com/system-security",
          },
          expanded: true,
          children: [
            {
              id: "os-security",
              title: "操作系统安全",
              description: "Windows/Linux安全配置",
              icon: <IconWithBackground><Server className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-blue-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "操作系统安全加固",
                provider: "网易云课堂",
                url: "https://example.com/os-security",
              },
              children: [],
            },
            {
              id: "endpoint-protection",
              title: "终端安全",
              description: "防病毒与终端防护",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-violet-600",
              difficulty: "中级",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "企业终端安全管理",
                provider: "腾讯云大学",
                url: "https://example.com/endpoint-security",
              },
              children: [],
            },
            {
              id: "access-control",
              title: "访问控制",
              description: "身份认证与权限管理",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-rose-600",
              difficulty: "中级",
              estimatedTime: "3-4周",
              recommendedCourse: {
                title: "访问控制与认证技术",
                provider: "极客时间",
                url: "https://example.com/access-control",
              },
              children: [],
            },
          ]
        },
        {
          id: "application-security",
          title: "应用安全",
          description: "保护Web与移动应用",
          icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-indigo-600",
          difficulty: "中级到高级",
          estimatedTime: "4-6个月",
          recommendedCourse: {
            title: "应用安全开发",
            provider: "极客时间",
            url: "https://example.com/app-security",
          },
          expanded: true,
          children: [
            {
              id: "web-security",
              title: "Web应用安全",
              description: "OWASP Top 10漏洞防护",
              icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-cyan-500",
              difficulty: "中级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "Web安全攻防实战",
                provider: "慕课网",
                url: "https://example.com/web-security",
              },
              children: [],
            },
            {
              id: "secure-coding",
              title: "安全编码",
              description: "代码安全与漏洞预防",
              icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "安全编码最佳实践",
                provider: "极客时间",
                url: "https://example.com/secure-coding",
              },
              children: [],
            },
            {
              id: "mobile-security",
              title: "移动应用安全",
              description: "Android/iOS安全开发",
              icon: <IconWithBackground><Code className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-emerald-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "移动应用安全指南",
                provider: "腾讯云大学",
                url: "https://example.com/mobile-security",
              },
              children: [],
            },
          ]
        },
        {
          id: "penetration-testing",
          title: "渗透测试",
          description: "安全漏洞评估与利用",
          icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-slate-700",
          difficulty: "高级",
          estimatedTime: "6-8个月",
          recommendedCourse: {
            title: "渗透测试实战",
            provider: "网易云课堂",
            url: "https://example.com/pentesting",
          },
          expanded: true,
          children: [
            {
              id: "reconnaissance",
              title: "信息收集",
              description: "目标侦察与漏洞扫描",
              icon: <IconWithBackground><Globe className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-blue-500",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "渗透测试信息收集",
                provider: "极客时间",
                url: "https://example.com/recon",
              },
              children: [],
            },
            {
              id: "vulnerability-exploit",
              title: "漏洞利用",
              description: "安全漏洞分析与利用",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-red-600",
              difficulty: "高级",
              estimatedTime: "6-8周",
              recommendedCourse: {
                title: "漏洞分析与利用",
                provider: "慕课网",
                url: "https://example.com/exploit",
              },
              children: [],
            },
            {
              id: "post-exploitation",
              title: "后渗透攻击",
              description: "权限提升与持久化技术",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-violet-600",
              difficulty: "高级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "后渗透技术实战",
                provider: "网易云课堂",
                url: "https://example.com/post-exploit",
              },
              children: [],
            },
          ]
        },
        {
          id: "security-management",
          title: "安全管理",
          description: "安全策略与风险管理",
          icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-teal-600",
          difficulty: "中级到高级",
          estimatedTime: "3-4个月",
          recommendedCourse: {
            title: "信息安全管理",
            provider: "极客时间",
            url: "https://example.com/security-management",
          },
          expanded: true,
          children: [
            {
              id: "risk-assessment",
              title: "风险评估",
              description: "威胁建模与风险分析",
              icon: <IconWithBackground><Shield className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-amber-600",
              difficulty: "中级",
              estimatedTime: "2-3周",
              recommendedCourse: {
                title: "游戏平台发布指南",
                provider: "极客时间",
                url: "https://example.com/game-platforms",
              },
              children: [],
            },
            {
              id: "game-marketing",
              title: "游戏营销",
              description: "宣传与用户获取",
              icon: <IconWithBackground><Lightbulb className="h-5 w-5 text-white" /></IconWithBackground>,
              color: "bg-rose-600",
              difficulty: "中级",
              estimatedTime: "4-6周",
              recommendedCourse: {
                title: "游戏营销策略",
                provider: "网易云课堂",
                url: "https://example.com/game-marketing",
              },
              children: [],
            },
          ]
        },
        {
          id: "compliance",
          title: "合规与标准",
          description: "安全法规与行业标准",
          icon: <IconWithBackground><BookOpen className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-blue-600",
          difficulty: "中级",
          estimatedTime: "2-3个月",
          recommendedCourse: {
            title: "网络安全法规与标准",
            provider: "网易云课堂",
            url: "https://example.com/cybersecurity-compliance",
          },
          expanded: true,
          children: []
        }
      ]
    }
  },
  {
    id: "biology",
    title: "生物学",
    description: "生物科学与分子生物学",
    icon: <IconWithBackground><Microscope className="h-5 w-5 text-white" /></IconWithBackground>,
    color: "bg-emerald-500",
    data: {
      id: "root",
      title: "生物学",
      description: "生物科学基础",
      icon: <IconWithBackground><Microscope className="h-5 w-5 text-white" /></IconWithBackground>,
      color: "bg-emerald-500",
      difficulty: "中级",
      estimatedTime: "4-5年",
      recommendedCourse: {
        title: "生物学导论",
        provider: "学堂在线",
        url: "https://example.com/biology-intro",
      },
      expanded: true,
      children: [
        {
          id: "molecular-biology",
          title: "分子生物学",
          description: "DNA、RNA与蛋白质",
          icon: <IconWithBackground><Beaker className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-lime-500",
          difficulty: "中级",
          estimatedTime: "6-8个月",
          recommendedCourse: {
            title: "分子生物学基础",
            provider: "Coursera",
            url: "https://example.com/molecular-biology",
          },
          expanded: true,
          children: []
        }
      ]
    }
  },
  {
    id: "medicine",
    title: "医学",
    description: "临床医学与医学研究",
    icon: <IconWithBackground><Heart className="h-5 w-5 text-white" /></IconWithBackground>,
    color: "bg-rose-500",
    data: {
      id: "root",
      title: "医学",
      description: "医学科学与临床医学",
      icon: <IconWithBackground><Heart className="h-5 w-5 text-white" /></IconWithBackground>,
      color: "bg-rose-500",
      difficulty: "高级",
      estimatedTime: "5-8年",
      recommendedCourse: {
        title: "医学导论",
        provider: "中国大学MOOC",
        url: "https://example.com/medicine-intro",
      },
      expanded: true,
      children: [
        {
          id: "anatomy",
          title: "人体解剖学",
          description: "人体结构与功能",
          icon: <IconWithBackground><Heart className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-pink-500",
          difficulty: "入门",
          estimatedTime: "4-6个月",
          recommendedCourse: {
            title: "系统解剖学",
            provider: "网易云课堂",
            url: "https://example.com/anatomy",
          },
          expanded: true,
          children: []
        }
      ]
    }
  },
  {
    id: "art-design",
    title: "艺术设计",
    description: "视觉艺术与设计原理",
    icon: <IconWithBackground><Palette className="h-5 w-5 text-white" /></IconWithBackground>,
    color: "bg-amber-500",
    data: {
      id: "root",
      title: "艺术设计",
      description: "艺术与设计基础",
      icon: <IconWithBackground><Palette className="h-5 w-5 text-white" /></IconWithBackground>,
      color: "bg-amber-500",
      difficulty: "中级",
      estimatedTime: "3-4年",
      recommendedCourse: {
        title: "设计原理",
        provider: "站酷课堂",
        url: "https://example.com/design-intro",
      },
      expanded: true,
      children: [
        {
          id: "graphic-design",
          title: "平面设计",
          description: "视觉传达与平面设计",
          icon: <IconWithBackground><PenTool className="h-5 w-5 text-white" /></IconWithBackground>,
          color: "bg-yellow-500",
          difficulty: "入门",
          estimatedTime: "6-8个月",
          recommendedCourse: {
            title: "平面设计基础",
            provider: "站酷课堂",
            url: "https://example.com/graphic-design",
          },
          expanded: true,
          children: []
        }
      ]
    }
  },
  {
    id: "business",
    title: "商业管理",
    description: "商业分析与管理技能",
    icon: <Lightbulb className="h-5 w-5 text-white" />,
    color: "bg-blue-600",
    data: {
      id: "root",
      title: "商业管理",
      description: "商业与管理基础",
      icon: <Lightbulb className="h-5 w-5 text-white" />,
      color: "bg-blue-600",
      difficulty: "中级",
      estimatedTime: "2-3年",
      recommendedCourse: {
        title: "商业管理导论",
        provider: "中国大学MOOC",
        url: "https://example.com/business-intro",
      },
      expanded: true,
      children: [
        {
          id: "marketing",
          title: "市场营销",
          description: "市场分析与营销策略",
          icon: <Lightbulb className="h-5 w-5 text-white" />,
          color: "bg-sky-500",
          difficulty: "入门",
          estimatedTime: "4-6个月",
          recommendedCourse: {
            title: "市场营销基础",
            provider: "网易云课堂",
            url: "https://example.com/marketing",
          },
          expanded: true,
          children: []
        }
      ]
    }
  }
]; 